# About the Project

## Abstract

The complex challenges in care for older adults generate an urgent need for system-thinking to identify effective 
and sustainable solutions. The development of age-friendly communities to promote active and healthy ageing is 
strongly supported, but knowledge of whether such initiatives are effective in terms of economic and quality-of-
life impacts is lacking.

## Project Objectives

The project aims to develop a model for long-term evaluation of 
municipal initiatives towards active and healthy ageing, with a focus on care and cooperation between different 
sectors and actors. 

### Specific research questions 

* What are the effects of a municipal Intervention Package concerning health, well-being, active ageing
and utilization of health care and social services?

* How are the effects distributed in the population, considering, for example, socioeconomic, gender, and
ethnicity dimensions?

* What resources are required and what are the costs of the Intervention Package?

* How do the effects of the Intervention Package impact resource distribution and costs related to the
ageing population, and how are these costs distributed across municipality, region and government
levels?

* How are the outcomes of the Intervention Package related to attitudes to age and ageing (i.e., ageism),
future outlook, intervention confidence, and readiness for change of older adults, their family
members/informal carers, and staff?

* What seems to be working and what does not, and how could the broad municipal initiative be redesigned
and optimized?

